repos:
-   repo: git://github.com/pre-commit/pre-commit-hooks
    sha: v1.2.3
    hooks:
    -   id: check-case-conflict
    -   id: check-executables-have-shebangs
    -   id: check-json
    -   id: check-merge-conflict
    -   id: check-symlinks
    -   id: check-xml
    -   id: check-yaml
    -   id: detect-private-key
    -   id: end-of-file-fixer
    -   id: file-contents-sorter
        files: .gitignore
    -   id: trailing-whitespace
    -   id: check-ast
    -   id: double-quote-string-fixer
    -   id: debug-statements
    -   id: mixed-line-ending
    -   id: name-tests-test
    -   id: requirements-txt-fixer
-   repo: git://github.com/pre-commit/mirrors-pylint
    sha: v1.8.3
    hooks:
    -   id: pylint
        args:
        - -d fixme
        - -d import-error
        - -d invalid-name
        - -d locally-disabled
        - -d missing-docstring
-   repo: git://github.com/Lucas-C/pre-commit-hooks
    sha: v1.1.5
    hooks:
    -   id: remove-tabs
-   repo: https://github.com/asottile/reorder_python_imports.git
    sha: v1.0.1
    hooks:
    -   id: reorder-python-imports
        language_version: python3.6
-   repo: https://github.com/asottile/pyupgrade
    sha: v1.2.0
    hooks:
    -   id: pyupgrade
        args: [--py3-plus]
